### ISSUE TITLE
running in docker, panicked at 'Controller not registered; what's wrong?

### ISSUE THREAD

**Issue by bugxzhu** [Phala-Network/phala-blockchain#239]
Starting pHost with extra opts '-r'
[2021-06-26T12:20:34Z WARN  substrate_subxt] The following types do not have registered type segmenters: {"ChainBridge::FungibleTransfer::U256", "PhalaMq::OutboundMessage::Message"} If any events containing these types are received, this can cause a `TypeSizeUnavailable` error and prevent decoding the actual event being listened for.Use `ClientBuilder::register_type_size` to register missing type sizes.
[2021-06-26T12:20:34Z INFO  phost] Connected to substrate at: ws://phala-node:9944
thread 'main' panicked at 'Controller not registered; qed', standalone/phost/src/main.rs:619:13
stack backtrace:
   0: std::panicking::begin_panic
   1: phost::bridge::{{closure}}
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: tokio::runtime::enter::Enter::block_on
   4: tokio::runtime::context::enter
   5: tokio::runtime::handle::Handle::enter
   6: phost::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by h4x3rotab** [comment]
Because as it says "Controller is not registered". The privkey you feed to the relayer (phost) must be a registered controller key. Are you running a local development environment? If so you can follow the our [hello world tutorial](https://wiki.phala.network/en-us/docs/developer/run-a-local-development-network/).

**Comment by bugxzhu** [comment]
> Because as it says "Controller is not registered". The privkey you feed to the relayer (phost) must be a registered controller key. Are you running a local development environment? If so you can follow the our [hello world tutorial](https://wiki.phala.network/en-us/docs/developer/run-a-local-development-network/).

yes，I have the controller account and bind the stash key.  Pruntime and node was up.


 docker ps
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED          STATUS          PORTS                                                                                                                                           NAMES
a9ee33966e53   swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-pruntime   "/bin/sh -c 'bash ./…"   10 minutes ago   Up 10 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                       phala-pruntime
ac91fa70b2e1   phalanetwork/phala-poc4-node                                "/bin/sh -c 'bash ./…"   11 minutes ago   Up 11 minutes   0.0.0.0:9933->9933/tcp, :::9933->9933/tcp, 0.0.0.0:9944->9944/tcp, :::9944->9944/tcp, 9615/tcp, 0.0.0.0:30333->30333/tcp, :::30333->30333/tcp   phala-node
root@chia:/data#

**Comment by bugxzhu** [comment]
[238878] 💸 new validator set of size 4 has been processed for era 67    
2021-06-28 12:26:35 ⚙️  Syncing 88.2 bps, target=#983584 (1 peers), best: #238938 (0x2100…85f2), finalized #238938 (0x2100…85f2), ⬇ 64.5kiB/s ⬆ 1.5kiB/s    
2021-06-28 12:26:40 ⚙️  Syncing 79.2 bps, target=#983585 (1 peers), best: #239334 (0x90d3…498d), finalized #239334 (0x90d3…498d), ⬇ 61.9kiB/s ⬆ 0.4kiB/s    
2021-06-28 12:26:45 ⚙️  Syncing 83.2 bps, target=#983586 (1 peers), best: #239750 (0xf5bc…c5d6), finalized #239750 (0xf5bc…c5d6), ⬇ 61.5kiB/s ⬆ 0.3kiB/s    
2021-06-28 12:26:50 ⚙️  Syncing 89.0 bps, target=#983587 (1 peers), best: #240195 (0x369c…1b22), finalized #240195 (0x369c…1b22), ⬇ 80.5kiB/s ⬆ 0.2kiB/s    
2021-06-28 12:26:55 ⚙️  Syncing 83.2 bps, target=#983588 (1 peers), best: #240611 (0x0125…4dd8), finalized #240611 (0x0125…4dd8), ⬇ 61.4kiB/s ⬆ 0.4kiB/s

**Comment by wcw84** [comment]
> Because as it says "Controller is not registered". The privkey you feed to the relayer (phost) must be a registered controller key. Are you running a local development environment? If so you can follow the our [hello world tutorial](https://wiki.phala.network/en-us/docs/developer/run-a-local-development-network/).

I have the same problem:

> # phala start phost debug
----------Start phala-phost----------
Starting PHost with extra opts '-r'
[2021-07-02T07:54:44Z INFO  phost] Connected to substrate at: ws://192.168.1.164:9944
thread 'main' panicked at 'Controller not registered; qed', standalone/phost/src/main.rs:573:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
----------Start phala-phost failed----------

My controller address is : 44RNAo2oMuPDGvnDjdr5xdj26X5nzfrGPPyVeo9akkCmEtQN , which had been bind to stash, the extrinsic is here:
https://phala.subscan.io/extrinsic/1022792-1

how to fix it?
Thanks in advanced!

**Comment by h4x3rotab** [comment]
Please double check you have set the correct mnemonic.

**Comment by wcw84** [comment]
> Please double check you have set the correct mnemonic.

I have fixed this problem: just wait the syncing of the node finished

**Comment by h4x3rotab** [comment]
In the new version it will not register the worker before the node is fully synced.
