### ISSUE TITLE
TCSNum limit at 32 is too low for high-end systems

### ISSUE THREAD

**Issue by PHA-SYSOPS** [Phala-Network/phala-blockchain#622]
if you have more than 28 cores in a system you will get errors:

[INFO  enclaveapp] [28] Benchmark thread started
thread 'bench-29' panicked at 'Run benchmark 29 failed', src/main.rs:684:25
stack backtrace:
[INFO  enclaveapp] [27] Benchmark thread started
   0: rust_begin_unwind
             at /rustc/798baebde1fe77e5a660490ec64e727a5d79970d/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/798baebde1fe77e5a660490ec64e727a5d79970d/library/std/src/panicking.rs:457:5
   2: app::main::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

The issue lies at the setting:

<TCSNum>32</TCSNum>

So it uses 4 threads for the app and then with -c 28 it will work, but does not utilize all 80 cores. New Xeon series have a theoretical limit of 92 cores, so raising this to above 96 makes sense.

**Comment by h4x3rotab** [comment]
Run multiple instance instead?

**Comment by PHA-SYSOPS** [comment]
on a physical host, that is not possible ... as there is no CPU pinning possible inside the host. 
Running VM's adds additional CPU loss with vSGX as its not optimized. Also DCAP is not supported in vSGX.
