### ISSUE TITLE
SGX_ERROR_UNEXPECTED when starting pruntime

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#80]
- Mode: Simulation (SGX_MODE=SW)
- SGX SDK: Version: 2.9.101.2

```log
thread 'main' panicked at '[-] Init Enclave Failed SGX_ERROR_UNEXPECTED!', src/main.rs:836:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d78d1d02761b906038ba4d54c5f3427f920f5fb/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9d78d1d02761b906038ba4d54c5f3427f920f5fb/library/std/src/panicking.rs:437:5
   2: app::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I will try to upgrade the SGX SDK.

**Comment by h4x3rotab** [comment]
This happens on AMD platform as well as some VM running on Intel CPUs. The Intel VMs on most VPS are fine. Still trying to figure out the problem behind.

**Comment by h4x3rotab** [comment]
It turned out it's a problem of CPUID. Proxmox VE doesn't set the CPUID by default. After turned the CUPID to the corresponding Intel version, everything works. Actually I don't think the SGX simulation mode requires anything special to run. So maybe by patching the SGX SDK, Ryzen CPUs can also run the simulation mode.
